### ISSUE TITLE
[AIRFLOW-4575] Operators using BigQueryHook need to provide location field

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#139] opened 2019-07-16 15:19 UTC
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4575

Lots of love

**Comment by nuclearpinguin** [comment] 2019-07-17 11:30
Duplicate of #140

**Closed by nuclearpinguin** 2019-07-17 11:30 UTC
Labels: JIRA
